module.exports = [
  {
    name: 'Nur Ali Rajab',
    age: 20,
    address: 'Jln Sotek',
    role: 'Owner',
    shopId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Helmi',
    age: 22,
    address: 'Jln batuah',
    role: 'Owner',
    shopId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Arwin Marinta',
    age: 20,
    address: 'Jln 3G',
    role: 'Owner',
    shopId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Andru',
    age: 20,
    address: 'Jln Sungai wein',
    role: 'Owner',
    shopId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Muhammad Saman',
    age: 23,
    address: 'Jln rambutan',
    role: 'Owner',
    shopId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
